server {
    listen 80;
    listen [::]:80;
    server_name ped.samdpi.uz www.ped.samdpi.uz;

    location = /favicon.ico {
        access_log off; log_not_found off;
    }
    location /static/ {
        root /home/ali/ped;
    }

    location /media/ {
        root /home/ali/ped;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/ped.sock;
    }
}